### ISSUE TITLE
Missing request headers

### ISSUE THREAD

**Issue by sivabalan02** [ngx-translate/http-loader#9]
Adding the request headers is missing like authorization is missing

**Comment by martinduris** [comment]
Hi,
something like this ?
https://github.com/senty/http-loader/commit/a445160efff1722ede7001dd588b2e43dcff03e3

created also PR:
https://github.com/ngx-translate/http-loader/pull/19

Martin

**Comment by ben-barbier** [comment]
yes, like this ;-)

**Comment by woteska** [comment]
Hi!

I have the same problem... I can't get any .json, because there is not option to set up headers to requests. Now, I can solve it within .htaccess file, but it is not a real solution.

Please, make it happen asap.

**Comment by ocombe** [comment]
The http loader is 15 lines (https://github.com/ngx-translate/http-loader/blob/master/src/http-loader.ts), just copy it and customize it the way you want.
You can copy the code from @martinduris.
  
I prefer to keep this loader minimal. If anyone wants this functionality, it's super simple to copy this code and use this instead, that's why I made the library modular, there will always be someone who needs a new thing on their loader.
